#!/bin/sh

objcopy -O binary $1 $2.tmp
desiredsize=$(nm $1 | grep '_end$' | cut -d' ' -f 1 | perl -e 'print hex(<>)')
startaddr=$(nm --debug-syms $1 | grep '.text$' | cut -d' ' -f 1 | perl -e 'print hex(<>)')
dd if=$2.tmp of=$2 bs=$(($desiredsize - $startaddr)) conv=sync
rm $2.tmp
